In [1]:
import numpy as np
import pandas as pd
import tensorflow as tf
import keras
import os

In [2]:
from keras.models import Sequential
from keras.layers import LSTM
from keras.layers import Dense
from keras.layers import Flatten

In [3]:
df=pd.read_csv("C:/Users/Anusha/OneDrive/Documents/VI SEM/IoT lab/IoT Mini project/sensor_sample.csv")

In [4]:
df

Time  Temperature_C  Temperature_F  Humidity  Pressure  \
0   2023/05/11_11-11-22           32.9          91.22        70      1007   
1   2023/05/11_11-12-22           32.9          91.22        70      1007   
2   2023/05/11_11-13-22           32.9          91.22        70      1007   
3   2023/05/11_11-14-22           32.9          91.22        68      1007   
4   2023/05/11_11-15-22           32.9          91.22        68      1007   
5   2023/05/11_11-16-22           32.9          91.22        68      1007   
6   2023/05/11_11-17-22           32.9          91.22        65      1007   
7   2023/05/11_11-18-22           32.9          91.22        65      1007   
8   2023/05/11_11-19-22           33.0          91.40        63      1007   
9   2023/05/11_11-20-22           33.0          91.40        63      1007   
10  2023/05/11_11-21-22           33.0          91.40        63      1007   
11  2023/05/11_11-22-22           33.0          91.40        63      1007   
12  2023/05/11_11-23-22           33.0          91.40        63      1007   
13  2023/05/11_11-24-22           33.0          91.40        63      1007   
14  2023/05/11_11-25-22           33.0          91.40        63      1007   
15  2023/05/11_11-26-22           33.0          91.40        63      1007   
16  2023/05/11_11-27-22           33.0          91.40        63      1007   
17  2023/05/11_11-28-22           33.0          91.40        63      1007   
18  2023/05/11_11-29-22           33.0          91.40        63      1007   
19  2023/05/11_11-30-22           33.0          91.40        63      1007   
20  2023/05/11_11-31-22           33.0          91.40        63      1007   
21  2023/05/11_11-32-22           33.0          91.40        63      1007   
22  2023/05/11_11-33-22           33.0          91.40        63      1007   
23  2023/05/11_11-34-22           33.0          91.40        63      1007   
24  2023/05/11_11-35-22           33.0          91.40        63      1007   

    Dripping status  
0               NaN  
1               NaN  
2               NaN  
3               NaN  
4               NaN  
5               NaN  
6               NaN  
7               NaN  
8               NaN  
9               NaN  
10              NaN  
11              NaN  
12              NaN  
13              NaN  
14              NaN  
15              NaN  
16              NaN  
17              NaN  
18              NaN  
19              NaN  
20              NaN  
21              NaN  
22              NaN  
23              NaN  
24              NaN

In [5]:
def prepare_data(timeseries_data, n_steps):
	X, y =[],[]
	for i in range(len(timeseries_data)):
		# find the end of this pattern
		end_ix = i + n_steps
		# check if we are beyond the sequence
		if end_ix > len(timeseries_data)-1:
			break
		# gather input and output parts of the pattern
		seq_x, seq_y = timeseries_data[i:end_ix], timeseries_data[end_ix]
		X.append(seq_x)
		y.append(seq_y)
	return np.array(X), np.array(y)

Temperature_C

In [6]:
#temperatrue-celsius
timeseries_data1=list(df['Temperature_C'])
n_steps=3
X, y = prepare_data(timeseries_data1, n_steps)

In [7]:
print(X),print(y)

[[32.9 32.9 32.9]
 [32.9 32.9 32.9]
 [32.9 32.9 32.9]
 [32.9 32.9 32.9]
 [32.9 32.9 32.9]
 [32.9 32.9 32.9]
 [32.9 32.9 33. ]
 [32.9 33.  33. ]
 [33.  33.  33. ]
 [33.  33.  33. ]
 [33.  33.  33. ]
 [33.  33.  33. ]
 [33.  33.  33. ]
 [33.  33.  33. ]
 [33.  33.  33. ]
 [33.  33.  33. ]
 [33.  33.  33. ]
 [33.  33.  33. ]
 [33.  33.  33. ]
 [33.  33.  33. ]
 [33.  33.  33. ]
 [33.  33.  33. ]]
[32.9 32.9 32.9 32.9 32.9 33.  33.  33.  33.  33.  33.  33.  33.  33.
 33.  33.  33.  33.  33.  33.  33.  33. ]


(None, None)

In [8]:
n_features = 1
X = X.reshape((X.shape[0], X.shape[1], n_features))
print(X)

[[[32.9]
  [32.9]
  [32.9]]

 [[32.9]
  [32.9]
  [32.9]]

 [[32.9]
  [32.9]
  [32.9]]

 [[32.9]
  [32.9]
  [32.9]]

 [[32.9]
  [32.9]
  [32.9]]

 [[32.9]
  [32.9]
  [32.9]]

 [[32.9]
  [32.9]
  [33. ]]

 [[32.9]
  [33. ]
  [33. ]]

 [[33. ]
  [33. ]
  [33. ]]

 [[33. ]
  [33. ]
  [33. ]]

 [[33. ]
  [33. ]
  [33. ]]

 [[33. ]
  [33. ]
  [33. ]]

 [[33. ]
  [33. ]
  [33. ]]

 [[33. ]
  [33. ]
  [33. ]]

 [[33. ]
  [33. ]
  [33. ]]

 [[33. ]
  [33. ]
  [33. ]]

 [[33. ]
  [33. ]
  [33. ]]

 [[33. ]
  [33. ]
  [33. ]]

 [[33. ]
  [33. ]
  [33. ]]

 [[33. ]
  [33. ]
  [33. ]]

 [[33. ]
  [33. ]
  [33. ]]

 [[33. ]
  [33. ]
  [33. ]]]


In [9]:
#define model
model = Sequential()
model.add(LSTM(50, activation='relu', return_sequences=True, input_shape=(n_steps, n_features)))
model.add(LSTM(50, activation='relu'))
model.add(Dense(1))
model.compile(optimizer = 'adam', loss='mse', metrics=['accuracy'])



In [10]:
# fit model
model.fit(X, y, epochs=100, verbose=0)

In [11]:
# demonstrate prediction for next 10 minutes
x_input = np.array(timeseries_data1[-4:-1])
temp_input=list(x_input)
lst_output=[]
i=0
while(i<10):
    
    if(len(temp_input)>3):
        x_input=np.array(temp_input[1:])
        #print("{} day input {}".format(i,x_input))
        #print(x_input)
        x_input = x_input.reshape((1, n_steps, n_features))
        #print(x_input)
        yhat = model.predict(x_input, verbose=0)
        #print("{} day output {}".format(i,yhat))
        temp_input.append(yhat[0][0])
        temp_input=temp_input[1:]
        #print(temp_input)
        lst_output.append(yhat[0][0])
        i=i+1
    else:
        x_input = x_input.reshape((1, n_steps, n_features))
        yhat = model.predict(x_input, verbose=0)
        #print(yhat[0])
        temp_input.append(yhat[0][0])
        lst_output.append(yhat[0][0])
        i=i+1
    
tc=[]
for i in lst_output:
  tc.append(np.round(i))
  
print(tc)

[33.0, 33.0, 33.0, 34.0, 34.0, 34.0, 34.0, 34.0, 35.0, 35.0]


Temperature_F

In [12]:
tf=[((9/5)*val+32) for i, val in enumerate(tc)]
print(tf)

[91.4, 91.4, 91.4, 93.2, 93.2, 93.2, 93.2, 93.2, 95.0, 95.0]


Humidity

In [13]:
timeseries_data2=list(df['Humidity'])
n_steps=3
X2, y2 = prepare_data(timeseries_data2, n_steps)

In [14]:
print(X2),print(y2)

[[70 70 70]
 [70 70 68]
 [70 68 68]
 [68 68 68]
 [68 68 65]
 [68 65 65]
 [65 65 63]
 [65 63 63]
 [63 63 63]
 [63 63 63]
 [63 63 63]
 [63 63 63]
 [63 63 63]
 [63 63 63]
 [63 63 63]
 [63 63 63]
 [63 63 63]
 [63 63 63]
 [63 63 63]
 [63 63 63]
 [63 63 63]
 [63 63 63]]
[68 68 68 65 65 63 63 63 63 63 63 63 63 63 63 63 63 63 63 63 63 63]


(None, None)

In [15]:
n_features = 1
X2 = X2.reshape((X2.shape[0], X2.shape[1], n_features))

In [16]:
print(X2)

[[[70]
  [70]
  [70]]

 [[70]
  [70]
  [68]]

 [[70]
  [68]
  [68]]

 [[68]
  [68]
  [68]]

 [[68]
  [68]
  [65]]

 [[68]
  [65]
  [65]]

 [[65]
  [65]
  [63]]

 [[65]
  [63]
  [63]]

 [[63]
  [63]
  [63]]

 [[63]
  [63]
  [63]]

 [[63]
  [63]
  [63]]

 [[63]
  [63]
  [63]]

 [[63]
  [63]
  [63]]

 [[63]
  [63]
  [63]]

 [[63]
  [63]
  [63]]

 [[63]
  [63]
  [63]]

 [[63]
  [63]
  [63]]

 [[63]
  [63]
  [63]]

 [[63]
  [63]
  [63]]

 [[63]
  [63]
  [63]]

 [[63]
  [63]
  [63]]

 [[63]
  [63]
  [63]]]


In [17]:
#define model
model2 = Sequential()
model2.add(LSTM(50, activation='relu', return_sequences=True, input_shape=(n_steps, n_features)))
model2.add(LSTM(50, activation='relu'))
model2.add(Dense(1))
model2.compile(optimizer = 'adam', loss='mse', metrics=['accuracy'])


In [18]:

# fit model
model2.fit(X2, y2, epochs=100, verbose=0)

In [19]:
# demonstrate prediction for next 10 days
x_input = np.array(timeseries_data2[-4:-1])
temp_input=list(x_input)
lst_output=[]
i=0
while(i<12):
    
    if(len(temp_input)>3):
        x_input=np.array(temp_input[1:])
        #print("{} day input {}".format(i,x_input))
        #print(x_input)
        x_input = x_input.reshape((1, n_steps, n_features))
        #print(x_input)
        yhat = model2.predict(x_input, verbose=0)
        #print("{} day output {}".format(i,yhat))
        temp_input.append(yhat[0][0])
        temp_input=temp_input[1:]
        #print(temp_input)
        lst_output.append(yhat[0][0])
        i=i+1
    else:
        x_input = x_input.reshape((1, n_steps, n_features))
        yhat = model2.predict(x_input, verbose=0)
        #print(yhat[0])
        temp_input.append(yhat[0][0])
        lst_output.append(yhat[0][0])
        i=i+1
    
hum=[]
for i in lst_output:
  hum.append(np.round(i))
  
print(hum)

[62.0, 62.0, 62.0, 61.0, 61.0, 61.0, 60.0, 60.0, 59.0, 59.0, 59.0, 58.0]


Pressure

In [20]:
timeseries_data3=list(df['Pressure'])
n_steps=3
X3, y3 = prepare_data(timeseries_data3, n_steps)

In [21]:
print(X3),print(y3)

[[1007 1007 1007]
 [1007 1007 1007]
 [1007 1007 1007]
 [1007 1007 1007]
 [1007 1007 1007]
 [1007 1007 1007]
 [1007 1007 1007]
 [1007 1007 1007]
 [1007 1007 1007]
 [1007 1007 1007]
 [1007 1007 1007]
 [1007 1007 1007]
 [1007 1007 1007]
 [1007 1007 1007]
 [1007 1007 1007]
 [1007 1007 1007]
 [1007 1007 1007]
 [1007 1007 1007]
 [1007 1007 1007]
 [1007 1007 1007]
 [1007 1007 1007]
 [1007 1007 1007]]
[1007 1007 1007 1007 1007 1007 1007 1007 1007 1007 1007 1007 1007 1007
 1007 1007 1007 1007 1007 1007 1007 1007]


(None, None)

In [22]:
n_features = 1
X3 = X3.reshape((X3.shape[0], X3.shape[1], n_features))

In [23]:
print(X3)

[[[1007]
  [1007]
  [1007]]

 [[1007]
  [1007]
  [1007]]

 [[1007]
  [1007]
  [1007]]

 [[1007]
  [1007]
  [1007]]

 [[1007]
  [1007]
  [1007]]

 [[1007]
  [1007]
  [1007]]

 [[1007]
  [1007]
  [1007]]

 [[1007]
  [1007]
  [1007]]

 [[1007]
  [1007]
  [1007]]

 [[1007]
  [1007]
  [1007]]

 [[1007]
  [1007]
  [1007]]

 [[1007]
  [1007]
  [1007]]

 [[1007]
  [1007]
  [1007]]

 [[1007]
  [1007]
  [1007]]

 [[1007]
  [1007]
  [1007]]

 [[1007]
  [1007]
  [1007]]

 [[1007]
  [1007]
  [1007]]

 [[1007]
  [1007]
  [1007]]

 [[1007]
  [1007]
  [1007]]

 [[1007]
  [1007]
  [1007]]

 [[1007]
  [1007]
  [1007]]

 [[1007]
  [1007]
  [1007]]]


In [24]:
#define model
model3 = Sequential()
model3.add(LSTM(50, activation='relu', return_sequences=True, input_shape=(n_steps, n_features)))
model3.add(LSTM(50, activation='relu'))
model3.add(Dense(1))
model3.compile(optimizer = 'adam', loss='mse', metrics=['accuracy'])


In [25]:

# fit model
model3.fit(X3, y3, epochs=100, verbose=0)

In [26]:
# demonstrate prediction for next 10 days
x_input = np.array(timeseries_data3[-4:-1])
temp_input=list(x_input)
lst_output=[]
i=0
while(i<12):
    
    if(len(temp_input)>3):
        x_input=np.array(temp_input[1:])
        #print("{} day input {}".format(i,x_input))
        #print(x_input)
        x_input = x_input.reshape((1, n_steps, n_features))
        #print(x_input)
        yhat = model.predict(x_input, verbose=0)
        #print("{} day output {}".format(i,yhat))
        temp_input.append(yhat[0][0])
        temp_input=temp_input[1:]
        #print(temp_input)
        lst_output.append(yhat[0][0])
        i=i+1
    else:
        x_input = x_input.reshape((1, n_steps, n_features))
        yhat = model.predict(x_input, verbose=0)
        #print(yhat[0])
        temp_input.append(yhat[0][0])
        lst_output.append(yhat[0][0])
        i=i+1
    
pres=[]
for i in lst_output:
  pres.append(np.round(i))
  
print(pres)

[1029.0, 1032.0, 1034.0, 1051.0, 1057.0, 1059.0, 1074.0, 1081.0, 1084.0, 1097.0, 1104.0, 1109.0]


In [27]:
!mkdir -p saved_model
model.save('C:/Users/Anusha/OneDrive/Documents/VI SEM/IoT lab/IoT Mini project/temp_c')
model2.save('C:/Users/Anusha/OneDrive/Documents/VI SEM/IoT lab/IoT Mini project/humidity')
model3.save('C:/Users/Anusha/OneDrive/Documents/VI SEM/IoT lab/IoT Mini project/pressure')

A subdirectory or file -p already exists.
Error occurred while processing: -p.
A subdirectory or file saved_model already exists.
Error occurred while processing: saved_model.


INFO:tensorflow:Assets written to: C:/Users/Anusha/OneDrive/Documents/VI SEM/IoT lab/IoT Mini project/temp_c\assets
INFO:tensorflow:Assets written to: C:/Users/Anusha/OneDrive/Documents/VI SEM/IoT lab/IoT Mini project/humidity\assets
INFO:tensorflow:Assets written to: C:/Users/Anusha/OneDrive/Documents/VI SEM/IoT lab/IoT Mini project/pressure\assets


Overall functions

In [28]:
#pred data prep
def prepare_data(timeseries_data, n_steps=3):
	X, y =[],[]
	for i in range(len(timeseries_data)):
		# find the end of this pattern
		end_ix = i + n_steps
		# check if we are beyond the sequence
		if end_ix > len(timeseries_data)-1:
			break
		# gather input and output parts of the pattern
		seq_x, seq_y = timeseries_data[i:end_ix], timeseries_data[end_ix]
		X.append(seq_x)
		y.append(seq_y)
	return np.array(X), np.array(y)
 
#functions to get individual output
def temp_c(data=list(df['Temperature_C'])[-10:], n_steps=3,n_features=1):
  X,y=prepare_data(data, n_steps)
  X = X.reshape((X.shape[0], X.shape[1],n_features))
  new_model = keras.models.load_model('C:/Users/Anusha/OneDrive/Documents/VI SEM/IoT lab/IoT Mini project/temp_c')
  new_model.fit(X,y,epochs=100,verbose=0)
  x_input=np.array(data[(-n_steps-1):-1])
  temp_input=list(x_input)
  lst_output=[]
  i=0
  while(i<10):
      
      if(len(temp_input)>3):
          x_input=np.array(temp_input[1:])
          x_input = x_input.reshape((1, n_steps, n_features))
          yhat = new_model.predict(x_input, verbose=0)
          temp_input.append(yhat[0][0])
          temp_input=temp_input[1:]
          lst_output.append(yhat[0][0])
          i=i+1
      else:
          x_input = x_input.reshape((1, n_steps, n_features))
          yhat = new_model.predict(x_input, verbose=0)
          temp_input.append(yhat[0][0])
          lst_output.append(yhat[0][0])
          i=i+1
      
  tc_out=[]
  for i in lst_output:
    tc_out.append(np.round(i))
    
  print('Predicted temperature (Celsius): \n',tc_out)
  tf_out=[((9/5)*val+32) for i, val in enumerate(tc_out)]
  print('Predicted temperature (Fahrenheit): \n',tf_out)
  # return tc_out,tf_out
  
#functions to get individual output
def humidity(data=list(df['Humidity'])[-10:], n_steps=3,n_features=1):
  X,y=prepare_data(data, n_steps)
  X = X.reshape((X.shape[0], X.shape[1],n_features))
  new_model = keras.models.load_model('C:/Users/Anusha/OneDrive/Documents/VI SEM/IoT lab/IoT Mini project/humidity')
  new_model.fit(X,y,epochs=100,verbose=0)
  x_input=np.array(data[(-n_steps-1):-1])
  temp_input=list(x_input)
  lst_output=[]
  i=0
  while(i<10):
      
      if(len(temp_input)>3):
          x_input=np.array(temp_input[1:])
          x_input = x_input.reshape((1, n_steps, n_features))
          yhat = new_model.predict(x_input, verbose=0)
          temp_input.append(yhat[0][0])
          temp_input=temp_input[1:]
          lst_output.append(yhat[0][0])
          i=i+1
      else:
          x_input = x_input.reshape((1, n_steps, n_features))
          yhat = new_model.predict(x_input, verbose=0)
          temp_input.append(yhat[0][0])
          lst_output.append(yhat[0][0])
          i=i+1
      
  hum_out=[]
  for i in lst_output:
    hum_out.append(np.round(i))
    
  print('Predicted Humidity: \n',hum_out)

def pressure(data=list(df['Pressure'])[-10:], n_steps=3,n_features=1):
  X,y=prepare_data(data, n_steps)
  X = X.reshape((X.shape[0], X.shape[1],n_features))
  new_model = keras.models.load_model('C:/Users/Anusha/OneDrive/Documents/VI SEM/IoT lab/IoT Mini project/pressure')
  new_model.fit(X,y,epochs=100,verbose=0)
  x_input=np.array(data[(-n_steps-1):-1])
  temp_input=list(x_input)
  lst_output=[]
  i=0
  while(i<10):
      
      if(len(temp_input)>3):
          x_input=np.array(temp_input[1:])
          x_input = x_input.reshape((1, n_steps, n_features))
          yhat = new_model.predict(x_input, verbose=0)
          temp_input.append(yhat[0][0])
          temp_input=temp_input[1:]
          lst_output.append(yhat[0][0])
          i=i+1
      else:
          x_input = x_input.reshape((1, n_steps, n_features))
          yhat = new_model.predict(x_input, verbose=0)
          temp_input.append(yhat[0][0])
          lst_output.append(yhat[0][0])
          i=i+1
      
  pres_out=[]
  for i in lst_output:
    pres_out.append(np.round(i))
    
  print('Predicted Pressure: \n',pres_out)
    


In [42]:
ttype(df[['Temperature_C']]

pandas.core.frame.DataFrame

In [45]:
t=[33,33,33,33,33,33,33,33.2,33.2,33.2]
h=[68,68,68,68,68,68,68,68,68,68]
p=[1007,1007,1007,1007,1007,1007,1007,1007,1007,1007]
temp_c(t,3,1) #now its returning..not printing
humidity(h,3,1)
pressure(p,3,1)

Predicted temperature (Celsius): 
 [33.0, 33.0, 33.0, 33.0, 33.0, 33.0, 33.0, 34.0, 34.0, 34.0]
Predicted temperature (Fahrenheit): 
 [91.4, 91.4, 91.4, 91.4, 91.4, 91.4, 91.4, 93.2, 93.2, 93.2]
Predicted Humidity: 
 [68.0, 68.0, 68.0, 68.0, 68.0, 68.0, 68.0, 68.0, 68.0, 68.0]
Predicted Pressure: 
 [1007.0, 1007.0, 1006.0, 1006.0, 1006.0, 1006.0, 1006.0, 1006.0, 1006.0, 1005.0]


In [30]:
# import pickle
# pickle.dump(model, open('model_temp.pkl', 'wb'))
# pickle.dump(model2, open('model_hum.pkl', 'wb'))
